language: objective-c
osx_image: xcode9
rvm:
  - 2.4.1
cache: bundler
matrix:
  include:
    - env: SDK=iphonesimulator PLATFORM="iOS Simulator,name=iPhone 6s,OS=11.0" SCHEME=ContentfulPersistence_iOS
    - env: SDK=appletvsimulator PLATFORM="tvOS Simulator,name=Apple TV 1080p,OS=11.0" SCHEME=ContentfulPersistence_tvOS
    - env: SDK=macosx PLATFORM="OS X" SCHEME=ContentfulPersistence_macOS
    - env: SWIFT_BUILD=true
script:
  - ./Scripts/travis-build-test.sh
after_success:
  - bundle exec slather coverage -s --coveralls 
  - pod lib lint ContentfulPersistenceSwift.podspec

